### ISSUE TITLE
Binary encoding of globals

### ISSUE THREAD

**Issue by mhk** [WebAssembly/spec#1032]
Short question, is it possible to deduct the value of a binary [global][1] without running a function that uses the global?

Example:
```
global:
74 00 41 7F

74 = i32 (valuetype)
00 = const (mut)
41 = i32.const (const instr)
7F = +127 unsigned LEB128, -1 signed LEB128 (i32)
```
So according to the *binary* specs [_Uninterpreted integers are encoded as signed integers._][2], however in the *syntac/struct* specs it says [_uninterpreted integers ... are represented as unsigned values_][3].

I am confused, could someone please clarify. Thank you.

[1]: https://webassembly.github.io/spec/core/binary/modules.html#binary-global
[2]: https://webassembly.github.io/spec/core/binary/values.html#binary-int
[3]: https://webassembly.github.io/spec/core/syntax/values.html#syntax-int

**Comment by rossberg** [comment]
Both statements are correct: in the *abstract syntax*, integer values are represented as unsigned numbers, because that matches the vast majority of their uses. Signed operations perform an explicit 2's complement reinterpretation (via the `signed` meta function in the spec).

However, in the *binary format*, integer values are encoded as signed LEB128, because that leads to a more compact encoding of values that are intended to be interpreted as (small) negative integers, which is a common enough case.

Neither determines whether the value is actually signed or not. That is up to use sites to decide.

So in your example, the SLEB value is -1, which encodes the i32 value 0xFFFF_FFFF in the abstract syntax.

FWIW, the text format allows both interpretations, and treats them as equivalent. That is, the value of the above global can be written as both (i32.const -1) or (i32.const 0xffff_ffff).

**Comment by mhk** [comment]
Thank you for your explanation.
