### ISSUE TITLE
When should resources be exhausted?

### ISSUE THREAD

**Issue by hjorthjort** [WebAssembly/spec#1060]
The core tests (for example [`fac.wast`](https://github.com/WebAssembly/spec/blob/master/test/core/fac.wast)) test for resource exhaustion with `assert_exhaustion`.

I can't find any mention of an absolute number that the call stack can't exceed in the spec or elsewhere. What's the intended behavior of `assert_exhaustion` -- that a program may either fail or return with a resource exhaustion error?

**Comment by sunfishcode** [comment]
There is no specific number specified. The purpose of `assert_exhaustion` tests is only to ensure that implementations have a limit. Implementations are not permitted to perform implicit tail-call optimization of recursive functions in a way that would allow them to recurse infinitely without trapping.

The `assert_exhaustion` test in `fac.wast` may be overzealous, because in theory an implementation could have a stack large enough to do that computation while still being finite. The test in call.wast is a better example; see [this comment](https://github.com/WebAssembly/spec/blob/master/test/core/call.wast#L96).

**Comment by hjorthjort** [comment]
Seems reasonable. Thanks for the clarification.
