### ISSUE TITLE
Spec Test Import Source

### ISSUE THREAD

**Issue by RyanLamansky** [WebAssembly/spec#1111]
In the spec tests, what's the source of the imports?  Example:
https://github.com/WebAssembly/spec/blob/e3a3c12f51221daaa901691e674d7ff990029122/test/core/data.wast#L27-L30

**Comment by rossberg** [comment]
They are assumed to defined by the "host". For example, the spec interpreter does it [here](https://github.com/WebAssembly/spec/blob/e3a3c12f51221daaa901691e674d7ff990029122/interpreter/host/spectest.ml).

This all has become somewhat unnecessary in the meantime, especially since test scripts nowadays allow "registering" modules for import themselves. I would love to remove spectest, but too many other more important things to do. But patches to the test suite are welcome. :)

**Comment by RyanLamansky** [comment]
That's helpful, thanks!

I'm not looking to improve the tests, just run them as they are to validate my own implementation 🙂
