### ISSUE TITLE
Wasm security holes?

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [WebAssembly/spec#1125]
Sorry if it's not the place to report this article, thanks to follow it up to the appropriate wasm repo if needed.
https://www.virusbulletin.com/virusbulletin/2018/10/dark-side-webassembly/

**Comment by Pauan** [comment]
Thanks, this has been partially covered in https://github.com/WebAssembly/spec/issues/1115

Basically, that article is misleading, Wasm cannot do anything that JS itself cannot do, so all of those exploits have already been possible for many years.

It has been possible for a long time to write asm.js code which is just as obfuscated (or more so) than Wasm code. And asm.js is within 2x native speed, so it's also very fast.

And it has always been possible to heavily obfuscate, encrypt, and dynamically eval JS code (as that article demonstrates). So Wasm isn't any worse in that regard.

Wasm does not create any new security holes (only the already-existing security holes in JS). In fact, Wasm is safer than JS, because it is always sandboxed, so it's much easier to verify which host APIs the Wasm is using.

The only argument that could be made is that if Wasm becomes more prevalent then that will make code auditing harder. I think that's a fair argument, but I don't think that's any worse than auditing obfuscated JS code, or auditing desktop code.

**Comment by rossberg** [comment]
To be fair, there is the practical concern that adding a complex new thing like Wasm to the platform requires tools like malware detectors to implement a lot of new analyses. That can take a long time to reach full maturity. However, that is not a problem specific to Wasm or its design, it is a general problem with adding any form of new functionality to the platform.

**Comment by ROBERT-MCDOWELL** [comment]
Does it mean that browser vendors will plan to have builtin wasm malware detection?
if not, what is the existing tools analazing the wasm binary and under which package are they offered? (extension?, conventional malware software? etc?)

**Comment by rossberg** [comment]
Not actionable for the spec, closing.
