### ISSUE TITLE
[spec] Clarity about min()/-1 in rem_s

### ISSUE THREAD

**Issue by axic** [WebAssembly/spec#1126]
Background: we are writing yet another wasm interpreter. So far we have only followed the spec to implement the interpreter and to write unit tests. Right now we are the point to execute the spectest cases.

The `(i32.rem_s (i32.const 0x80000000) (i32.const -1))` case (https://github.com/WebAssembly/spec/blob/master/test/core/i32.wast#L107) failed. The same applies to `i64.rem_s`.

On page 40 of the spec there is a note for `idiv_s`:
> Besides division by 0, the result of (−2^𝑁−1)/(−1) = +2^𝑁−1 is not representable as an 𝑁-bit signed integer.

Under `irem_s`:
> As long as both operators are defined, it holds that 𝑖1 = 𝑖2 · idiv_s(𝑖1, 𝑖2) + irem_s(𝑖1, 𝑖2).

Probably we should have deducted from this comment to check the edge cases of `idiv_s` first.

On page 65:
> Where the underlying operators are partial, the corresponding instruction will trap when the result is not defined.

However, according to the test case, `rem_s` will not trap, but return 0. Likely I am missing something, but I think page 40 could be made a bit more clear regarding `rem_s`.

**Comment by rossberg** [comment]
Hm, can you clarify what contradiction you see? The specification of irem_s only returns undefined for the 0 case. Why would you expect it to trap for the other case?

The note about the relation between idiv_s and irem_s also seems correct to me: as stated, the equation does not apply to the min/-1 case, because idiv_s is not defined for that case (even though irem_s is).

**Comment by rossberg** [comment]
I believe this has been answered.
