### ISSUE TITLE
[Question] Is it possible to change the `this` context of exported functions?

### ISSUE THREAD

**Issue by tyronedougherty** [WebAssembly/spec#1260]
I've been trying out WebAssembly using [AssemblyScript](https://github.com/AssemblyScript/assemblyscript) and have found it to be a great experience thus far.

One thing I'm not particularly clear on is if it is possible to change the `this` context of a function that is exported from WebAssembly?

A contrived example might be:

```
window.val = 5;

class Example {
   constructor() { this.val = 3 }
}

const newContext = new Example();

function returnVal() {
   return this.val;
}

WebAssembly.instantiateStreaming(
        fetch('./build/optimized.wasm'),
        {
            env: {
                returnValFn: returnVal
            }
        }
    )
   .then(
        // This always console logs `5`, even though I want it to log `3`
        (module) => console.log(module.instance.exports.returnValFn.call(newContext))
    );
```

So far, all my efforts to change the `this` context of the exported function have not worked - it always seems to maintain the `window` as the context for the function no matter what I do.

I'm wondering if this is a limitation within just AssemblyScript or within WebAssembly itself.

Would much appreciate some help on this issue! 😄

**Comment by Ms2ger** [comment]
The spec currently doesn't support this, because wasm functions don't have the concept of this value.

More specifically, `module.instance.exports.returnValFn` is an "Exported Function" whose WebAssembly function address refers to a "host function". When you call it, any arguments are converted to corresponding wasm values, and the "host function" is called through `func_invoke()`, which doesn't accept a this value; and "run a host function" passes **undefined** as the this value - because it doesn't have access to anything else.

**Comment by tyronedougherty** [comment]
I see! Very interesting - thank you for the detailed explanation!

Sadly it seems what I'm trying to do is impossible then.

Does this feature happen to be on any kind of roadmap, or is it out of the question?

**Comment by Ms2ger** [comment]
I coincidentally found https://github.com/WebAssembly/js-types/issues/21 which is related. Note that this is a very early proposal with a lot of questions around it, though.

**Comment by rossberg** [comment]
Closing as answered.
