### ISSUE TITLE
[Question] Run-time conformance tests?

### ISSUE THREAD

**Issue by TylerNowicki** [WebAssembly/spec#1275]
Hi,

I am interested in validating the completeness of different stand-lone run-times. Are the core tests sufficient for evaluating a run-time's conformance with the standard?

My skepticism is because there are not very many tests wast tests here and I noticed that run.py, which is used to bulk run wast tests, assumes it is using the reference run-time. For example, wasmer does not support the -d option. Run.py uses -d with the reference run-time to generate a bin.wast files. In addition the run-time also assumes the --wasm input is a file path (it fails if args are included in the file path). Unfortunately, other run-times require additional args to run wast files, for example, "wasmer wast <file>.wast". This makes it appear as though the tests in core are only for evaluating the reference implementation, not spec compliance of other run-times.

Ideally, I am looking for a test-suite to validate that a given run-time implements the standard faithfully and additional tests for each phase 3 proposal. Does anything like this exist?

Tyler

**Comment by rossberg** [comment]
Yes, the test suite is supposed to be comprehensive, and it is used by all production engines. Note that each file contains many different tests of a particular feature.

The runner script in that directory is mostly specific to the reference interpreter, though. Since there is no common standard for command line invocation, engines typically need to write their own version of this script, but that should be easy. The repo already contains two other runners to be used in JS embeddings like browsers.

**Comment by TylerNowicki** [comment]
Thank you!
