### ISSUE TITLE
Can Wasm fully exploit the Apple M1 and other CPUs based on many specialised co-processors?

### ISSUE THREAD

**Issue by carlyounger** [WebAssembly/spec#1276]
One of the things that makes Apple Silicon so fast (and fascinating) is the way the CPU is assisted by a range of specialised co-processors, such as the M1's 16-core neural engine.

Having a generic ISA, WebAssembly provides no way to interact with these kinds of co-processors directly, so I wondered if they will always be redundant when executing Wasm code??

This is not really a question about the M1, or even Apple Silicon, in particular. Thinking longer term, if the world moves towards RISC CPUs with many specialised co-processors, will Wasm be able to expose that functionality to the Web?

**Comment by lars-t-hansen** [comment]
There is some discussion about related matters in the SIMD repo, since a number of SIMD instructions on various architectures that are important for performance have semantics that are not necessarily easily mirrored to other architectures than the one each instruction is native to.  (Eg PMADDUBSW is Intel-specific and important for neural network simulations, but IIRC the corresponding instruction on ARM64 has semantics that differ in edge cases.)  A next step for the SIMD work is likely going to be to find some way of incorporating these platform-specific instructions without papering over their platform-specificness.

**Comment by carlyounger** [comment]
Thank you, @lars-t-hansen. I'll follow the discussion on the SIMD repo.
