### ISSUE TITLE
[WAT Spec] Elem and Data single instructions abbreviations missing parens

### ISSUE THREAD

**Issue by laelath** [WebAssembly/spec#1319]
The single-instruction abbreviations for both [elem](https://webassembly.github.io/spec/core/text/modules.html#id7) and [data](https://webassembly.github.io/spec/core/text/modules.html#id8) segments according to the spec should not be parenthesized, but in practice parsers like `wat2wasm` and `wasmtime` require the instructions be in parentheses.

I also noticed the implementations restrict the `offset` abbreviations to be either `i32.const` or `global.get`, and `item` abbreviations to be either `ref.null` or `ref.func`.

**Comment by rossberg** [comment]
Right. Moving forward, these should probably allow folded instructions, but for now that doesn't matter. Fixed in #1321. I also added a number of negative tests around the kind of instructions allowed as offsets or items. However, in practice any of the other leads to a validation error anyway, so it's fine for engines to rule them out either way.
