### ISSUE TITLE
If a module's start function fails, is the module instantiated?

### ISSUE THREAD

**Issue by TonyGuil** [WebAssembly/spec#1356]
If a module's <tt>start</tt> function fails, is the module instantiated? I would assume not. But that invalidates the very last test in <tt>linking.wast</tt>. The module's <tt>start</tt> function executes an <tt>unreachable</tt> instruction, and traps. So according to my interpreter, the module has not been instantiated. But then we get (Line 388):
<pre>(assert_return (invoke $Ms "get table[0]") (i32.const 0xdead))</pre>
and this is supposed to call function <tt>$f</tt> in the uninstantiated module, via a table element in a previously instantiated module <tt>$Ms</tt>. My interpreter accordingly generates an <tt>uninitialized</tt> error, but the test suite expects the call to succeed.

Is this right? Or have I missed something?

**Comment by rossberg** [comment]
Well, since there is an explicit test for this you can assume it is intentional. 

Conceptually, the start function is just a function that is called automatically after the module has been initialised. At this point, imported memories and tables have already been updated, potentially with functions from the modules. It would complicate both semantics and implementations if there was a requirement to roll that back: semantically, there either would have be some implicit mutation to tables, or function values themselves would have to be defined to be mutable. Both are rather undesirable properties and complications.

**Comment by TonyGuil** [comment]
I am not suggesting that changes to memories and tables be rolled back. But according to the spec (page 18):
<pre>The start function is intended for initializing the state of a module. The module and its exports are not
accessible before this initialization has completed.</pre>
So, although memories and tables have been initialized, the module itself has not, if the start function traps. Hence (presumably) its functions can't be called. I think the test would make more sense if the module's table was initialized with an imported function, that could safely be called.

**Comment by TonyGuil** [comment]
@conrad-watt, you are strenthening my case! If the start function fails, then (in your example) the memory allocator might be in an invalid state. So we can't call any functions in the module, because who knows what might happen?

I agree that the entry in the imported table should be initialized to <tt>$f</tt>. What I am saying is that when this function is _called_ indirectly by <tt>get table[0]</tt> in the <tt>assert_return</tt> test on line 388, this call should fail. Imagine what might happen if <tt>$f</tt> tried to allocate memory!

So there should in fact be _two_ tests: the original test, but altered to expect an error "uninstantiated module" or some such; and a new test, which initializes the table entry to an _imported_ function from a different module, that can safely be called.

**Comment by conrad-watt** [comment]
>  If the start function fails, then (in your example) the memory allocator might be in an invalid state. So we can't call any functions in the module, because who knows what might happen?

There would be an error in the functional behaviour of the compiled program, but nothing unsafe would happen from the perspective of the Wasm VM. It's not the language's responsibility to mitigate against these logic bugs - hardening can be inserted by the source language compilation scheme if it's deemed appropriate (e.g. by programmatically checking that the start function successfully executed).

> What I am saying is that when this function is called indirectly by `get table[0]` in the `assert_return` test on line 388, this call should fail.

It is very unlikely that this behaviour will be changed now, because it would cause a web compat issue. In any case, I believe the current behaviour is preferable.

**Comment by rossberg** [comment]
I agree that the current behaviour is preferable, for the reasons mentioned above. Specifically, it avoids inducing stateful semantics into values that do not otherwise have state (esp function and module instances).

**Comment by rossberg** [comment]
This has been answered.
