### ISSUE TITLE
Encoding of prefix in data segment entries

### ISSUE THREAD

**Issue by nagisa** [WebAssembly/spec#1439]
Hi,

In WebAssembly 1.0 the data segment encoding was specified as

```
datasec ::= vec(data)
data ::= memidx expr vec(byte)
```

and with the merge of `bulk-memory` proposal (AFAIU) it has become

```
datasec ::= vec(data)
data ::= 0x00 expr vec(byte)
       | 0x01 vec(byte)
       | 0x02 memidx expr vec(byte)
```

This sort of seems backwards-compatible at a first glance, but it isn't actually due to `memidx` using the LEB128 encoding. This means that in the original specification `00`, `80 00`, `80 80 00`, `80 80 80 00`, `80 80 80 80 00` were all valid prefix bitstream patterns for the `data`. As a result binary encoded modules that were valid as per the currently published WebAssembly specification are no longer valid in the draft.

I wonder if it would make sense to adjust the description of the `data` as such:

```
datasec ::= vec(data)
data ::= 0x00 expr vec(byte)
       | 0x01 vec(byte)
       | 0x02 memidx expr vec(byte)
       | 0x80 0x00 expr vec(byte)
       | 0x80 0x80 0x00 expr vec(byte)
       | 0x80 0x80 0x80 0x00 expr vec(byte)
       | 0x80 0x80 0x80 0x80 0x00 expr vec(byte)
```

or perhaps even

```
datasec ::= vec(data)
data ::= 0x00 expr vec(byte)
       | 0x01 vec(byte)
       | 0x02 memidx expr vec(byte)
       | 0x80 memidx expr vec(byte) // note, though that it ends up accepting `80 80 80 80 80 00` as an additional valid encoding.
```

in order to maintain the backwards compatibility? Seems like it'd be a pretty painless change to make.

**Comment by nagisa** [comment]
I haven't checked too closely if there are other occurrences of this, but at least the element section entries are also effected in much the same way.

**Comment by nagisa** [comment]
All implementations of what, specifically? Producers? Consumers? On the consumer side of things the wasm-tools' wasmparser will happily validate any LEB encoding of `0` for `memidx` since the very first iterations of the project, as far as I can tell. On the producer side… a fuzzer comes to mind as something that could produce arbitrary LEB encoding of `0`.

**Comment by rossberg** [comment]
The interpreter actually maintains backwards compatibility by deliberately using the equivalent of
```
data ::= i:u32 expr vec(byte)          (if i = 0)
      |  i:u32 vec(byte)               (if i = 1)
      |  i:u32 memidx expr vec(byte)   (if i = 2)
```
But I hadn't noticed the discrepancy with the spec, which uses single bytes. Not sure if that was intentional. I'm fine resolving it either way, though I would generally be hesitant to break backwards compatibility if there isn't a strong reason?

**Comment by alexcrichton** [comment]
My recollection was that this was intentional breakage in the reference types and bulk memory proposals. I found https://github.com/WebAssembly/bulk-memory-operations/issues/153 as an example of historical discussion, although I am unable to find more references.

I figured it'd be good to look at what implementations do. I'm not familiar with all of these so I'm not 100% sure these classifications are correct:

| engine | data | element |
|---------|-----|----------|
| v8 | [32-bit leb](https://github.com/v8/v8/blob/c93098f2729797a75b9b7d146760d3a3c85d06f1/src/wasm/module-decoder.cc#L2172) |  [32-bit leb](https://github.com/v8/v8/blob/c93098f2729797a75b9b7d146760d3a3c85d06f1/src/wasm/module-decoder.cc#L2080)
| spidermonkey | [32-bit leb](https://searchfox.org/mozilla-central/source/js/src/wasm/WasmValidate.cpp#2904) | [32-bit leb](https://searchfox.org/mozilla-central/source/js/src/wasm/WasmValidate.cpp#2528) |
| jsc | [32-bit leb](https://github.com/WebKit/WebKit/blob/62ef3d6a312d90cc54d8c45087210c0f4ffff156/Source/JavaScriptCore/wasm/WasmSectionParser.cpp#L775) | [single byte](https://github.com/WebKit/WebKit/blob/62ef3d6a312d90cc54d8c45087210c0f4ffff156/Source/JavaScriptCore/wasm/WasmSectionParser.cpp#L414-L415) | 
| wasmtime | [32-bit leb](https://github.com/bytecodealliance/wasm-tools/blob/af8db28b5af7a46a78f7884110ae6517b807b02b/crates/wasmparser/src/readers/core/data.rs#L118) | [32-bit leb](https://github.com/bytecodealliance/wasm-tools/blob/af8db28b5af7a46a78f7884110ae6517b807b02b/crates/wasmparser/src/readers/core/elements.rs#L225) |

This sort of makes sense to me in that to pass spec tests prior to bulk memory and reference types data/element segments had to decode a 32-bit leb, and so it's unlikely to go back and remove that (also spec tests currently still require it). I can say that at least for Wasmtime's implementation it was my intention to eventually go back and remove the 32-bit leb support to match with the spec, but I hadn't gotten around to that.

**Comment by alexcrichton** [comment]
I don't believe this was the only breakage relative to the original spec in the bulk memory proposal. This module:

```wasm
(module
  (import "" "" (memory 0))
  (data (i32.const 0) "abc")
  (data (i32.const -1) "123")
)
```

is semantically different today than it was historically. The original version of the spec would have this module fail instantiation altogether with no writes happening to the imported memory. The current version of the spec writes the first data segment into memory and then fails instantiation on the second one.

IIRC the discussions at the time about this concluded that the "breakage" was acceptable since it was deemed to never actually happen in practice so changing the spec seemed fine. I don't recall, though, how this was evaluated.

**Comment by rossberg** [comment]
@alexcrichton, I see what you mean, but technically, allowing a previously invalid module to become valid isn't regarded a breaking change. If it was, we could never extend Wasm at all.

**Comment by rossberg** [comment]
During an attempt to adapt the interpreter to match the spec, I noticed that the current test suite actually contains multiple tests (in binary.wast and binary-leb128.wast) for allowing multi-byte LEB values as data and element segment tags.

That made me question the claim made earlier in this thread that most engines rejected multi-byte encodings before or do now. So I did a couple of experiments with both Safari and Chrome, and they both allow multi-byte encodings of the section kind.

(I didn't test Firefox, since I don't have it installed, but I assume it passes the current test suite as well? @lars-t-hansen)

So it seems like the spec indeed should be fixed to match test suite and (major) implementations, and thereby also restore proper backwards compatibility.

**Comment by lars-t-hansen** [comment]
@rossberg, Weirdly we do not have those test cases in our test suite, but we do read data and element segment flags as VarU32 - up to five bytes.  I think this corresponds to what @alexcrichton says [above](https://github.com/WebAssembly/spec/issues/1439#issuecomment-1088922572).

**Comment by rossberg** [comment]
Okay, great, thanks for checking @lars-t-hansen.

**Comment by rossberg** [comment]
> I think this corresponds to what @alexcrichton says [above](https://github.com/WebAssembly/spec/issues/1439#issuecomment-1088922572).

Indeed, thanks for pointing out. I somehow had managed to overlook his reply. Thanks @alexcrichton for testing!

So I guess we can treat #1461 as fixing an oversight in the spec.

**Comment by tlively** [comment]
Fixing the spec to restore back compat sounds good to me.

**Comment by rossberg** [comment]
Okay, I'll land #1461 then.
