### ISSUE TITLE
does `funcref` require gc to implement?

### ISSUE THREAD

**Issue by yamt** [WebAssembly/spec#1513]
i'm trying to implement a runtime in C.
because `funcref` values can be freely produced by instances (either with elements or `ref.func`)
and they can be passed among instances, i can't imagine any reasonable way for a runtime without gc to know when it's safe to "free" a function which might be referenced by `funcref` values.
am i missing something?

**Comment by tlively** [comment]
You'll definitely need to do reference counting, but `funcref` can't form cycles with other `funcref` values, so you shouldn't need a full GC.

**Comment by yamt** [comment]
> You'll definitely need to do reference counting, but `funcref` can't form cycles with other `funcref` values, so you shouldn't need a full GC.

thank you.
but why can't it form cycles?
i couldn't find anything preventing it.
eg. funcref -> function -> table -> funcref

also, i feel reference counting for each `funcref` values is a bit unrealistic as it would be very expensive to track every copies of a `funcref`.

**Comment by tlively** [comment]
Ah, I guess you're right about the cycles if your tables and globals and things would be eligible to become garbage as well. @rossberg, is there something we're missing here?

**Comment by rossberg** [comment]
No, that's correct. It has been the case since Wasm 1.0 that you can create a cycle between module instances by initialising table entries in one with functions from another (and with Wasm 2.0, also through globals instead of table). If an engine wants to reliably reclaim instances dynamically, then it has to implement some memory management policy that can detect such cycles. Since all the respective data structures are under control of the engine, that may be somewhat simpler than a typical GC.

I don't remember if we had any specific discussion of this, but perhaps the assumption was that most non-Web, AOT-style stand-alone engines are more "static", and not interested in reclaiming modules until the program terminates. That may not actually be true. In any case, the problem seems unavoidable.

**Comment by yamt** [comment]
ok.
while it's unfortunate for my implementation, i can work it around. probably the simplest thing is only to allow destroying instances as a group.
thank you!

**Comment by rossberg** [comment]
Closing as answered.
