### ISSUE TITLE
relax the var to allow utf8 encoding in the wat syntax

### ISSUE THREAD

**Issue by bobzhang** [WebAssembly/spec#1618]
According to the reference interpreter

```ocaml
let symbol =
  ['+''-''*''/''\\''^''~''=''<''>''!''?''@''#''$''%''&''|'':''`''.''\'']
let letter = ['a'-'z''A'-'Z']
let idchar = letter | digit | '_' | symbol
let name = idchar+
let id = '$' name

  | id as s { VAR s }

```

Currently I can only write ascii letters in the wat syntax, `(local $var)`. 
It is a bit awkward to encode other utf8 letters in the wat syntax, 
so people can write `(local $你好)`. 

It is a bit worse in the current situation, since no escaping syntax supported so 
we have to do some magic encoding here

**Comment by bobzhang** [comment]
seems to be relevant to #617, the title is a bit misleading, it is not strange symbols though

**Comment by rossberg** [comment]
Yes, this is as spec'ed in the standard, and it is rather intentional that program text (outside strings and comments) is limited to plain ASCII. Unicode identifiers are a can of worms, as explained in the other issue.

The ability to annotate richer print names is part of the [annotations proposal](https://github.com/WebAssembly/annotations).

**Comment by rossberg** [comment]
With the annotations proposal (Wasm 3) we now support string-escaping arbitrary Unicode as identifiers, so I think we can close this.
