### ISSUE TITLE
Do there any JS APIs for accessing the WASM GC type?

### ISSUE THREAD

**Issue by zhenweijin** [WebAssembly/spec#1646]
Hi, 
Maybe my question is stupid, Currently, if we want to access GC type value through js-api, it output `object`, I wonder if there have JS APIs to access the fields of wasm gc type value? V8 have already provide C++ related APIs to access them, but in JS it seems not support yet.  I would like to know if the JavaScript API will support this feature in the future, and if not, what are the challenges?

Thanks.

**Comment by rossberg** [comment]
The initial API is described here: https://github.com/WebAssembly/gc/blob/main/proposals/gc/MVP-JS.md

It indeed does not offer much in the way of accessing GC objects from JS. That was left for future versions, because such an API is far from trivial (e.g., all the Wasm type structure needs to be reflected in JS), and it unclear what exactly it should offer.

**Comment by zhenweijin** [comment]
> The initial API is described here: https://github.com/WebAssembly/gc/blob/main/proposals/gc/MVP-JS.md
> 
> It indeed does not offer much in the way of accessing GC objects from JS. That was left for future versions, because such an API is far from trivial (e.g., all the Wasm type structure needs to be reflected in JS), and it's not clear what exactly it should offer.

get it, thanks for your reply.
