### ISSUE TITLE
Text format typos

### ISSUE THREAD

**Issue by verbessern** [WebAssembly/spec#1809]
In the instructions text format there are missing: extadd_pairwise_i16x8_u, and for the f64x2/f32x4 the ceil, floor, trunc, and nearest.

The fNxM.add instruction in the change history vector instructions list is separated from its "group" with fNxM.sub, not only in this proposal.

Also the ordering of the instructions in the binary and the text sections is a bit different in some groups of instructions, just saying.

**Comment by rossberg** [comment]
Thanks. I transferred this issue, since these are upstream problems. Added the missing extadd instructions and restructured the changes enumerations. The missing rounding instructions were already fixed upstream. Not sure if this is still going to get downstreamed, since exceptions have already been merged.

FWIW, the [github.io page](https://webassembly.github.io/spec/) now has a link to a recent 3.0 draft that should include the most up-to-date versions of all already-merged proposal specs (including exceptions).
