### ISSUE TITLE
Same test expected to result in different error messages

### ISSUE THREAD

**Issue by csjh** [WebAssembly/spec#1841]
https://github.com/WebAssembly/spec/blob/1904486128cbbb35e4c6e3b3e2b789be484cb40c/test/core/data.wast#L298

https://github.com/WebAssembly/spec/blob/1904486128cbbb35e4c6e3b3e2b789be484cb40c/test/core/data.wast#L319

The above 2 tests seem to generate the same bytes, but two different error messages are expected from them. Not too sure which to interpret as the correct one.

**Comment by keithw** [comment]
I believe the spec interpreter only requires the expected error message to be a prefix of its actual error message, and in #1076 and #1089, the expected error messages at the time were edited to remove the indices (so that implementations wouldn't be required to produce a dynamically formatted string at execution-time). Some later tests have come in after this...

**Comment by csjh** [comment]
Interesting - are some of these test quirks documented anywhere? There's a few I've picked up on (spectest globals initializing with the value 666 comes to mind) which are a bit hard to pick up on w/o asking around

**Comment by rossberg** [comment]
Unfortunately, not really. The closest you get to documentation for the .wast format is [here](https://github.com/WebAssembly/spec/blob/main/interpreter/README.md#scripts). At least the signature of the spectest module is listed there as well, though not its values.

I'll add that information to that doc.

**Comment by rossberg** [comment]
Done.

**Comment by csjh** [comment]
Thanks!
