### ISSUE TITLE
Clarification on LEB128 Error Interpretation in Binary Function Type Test

### ISSUE THREAD

**Issue by chobie** [WebAssembly/spec#1853]
Hello. I am currently creating an interpreter for WebAssembly 2.0 and have a question about the specification of LEB128.

In the binary-leb128 tests, there is the following test case. From my understanding, it seems to be an error for any fixed byte value other than 0x60. However, the test case seems to interpret it as a u8 LEB128 error.

https://github.com/WebAssembly/spec/blob/main/test/core/binary-leb128.wast#L1078

```
"\e0\7f"                  ;; Malformed functype, -0x20 in signed LEB128 encoding
```

Looking at the draft specification:  
https://webassembly.github.io/spec/core/binary/types.html#binary-functype

> Function types are encoded by the byte `0x60`

Given this, should this test case be interpreted as an error for values other than 0x60, or should it be treated as a u8 LEB128 error? Which interpretation is more appropriate?

**Comment by rossberg** [comment]
The value 0x60 happens to be the 1-byte SLEB encoding of -0x20 (and there are places where (other) type codes and LEBs overlap, e.g., for block types). This test ensures that, nevertheless, it is not accidentally encoded as a 2-byte SLEB representation for the same value.

The error message for the reference interpreter originates from the fact that it decodes this byte as an s7, because it interprets all bytes as some uN or sN. But that is equivalent. You can interpret the error in whatever way you prefer.

**Comment by chobie** [comment]
Thank you for the clear explanation. I had been using test cases to check compliance with the specification, but since I was only thinking about the decoding process, it seems I misinterpreted the results.

I was unsure whether my implementation should output `integer representation too long` or `integer too large`, but this has now been resolved. Your explanation also helped deepen my understanding of the reference interpreter. Thank you very much.
