### ISSUE TITLE
Change memory sizes to be in units of the page size.

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/spec#208]
Could we change the memory sizes, in the memory section for the min and max and in grow-memory to be in units of the pages size which is 64k?

Other sizes for the min and max can not even be encoded in the binary format, and it's just a burden for consumers and producers to have to be rounding these off and scaling them.

This will avoid the need for page size error checking in grow-memory.

**Comment by kg** [comment]
Locking the unit to 64k would prevent us from changing the page size constraints in the future (there are some mentions of this in the design repo). So I think it probably needs to be in bytes.

**Comment by JSStats** [comment]
It was already decided to have just one page size and go with that. There is/was consensus to change the v8 encoding to units of the pages size, and less significant bits are just noise in the wast and a challenge to define how they map to the binary encoding? Happy to close this as it is just a wast suggestion and the deployment encoding is going to page sized units.

**Comment by JSStats** [comment]
Give up on this, keeping them as bytes. There are spec tests imported into other tools such as sexpr-wasm-prototype that would require coordination.

**Comment by lukewagner** [comment]
The point of the wasm page size constant is to not change in the future (after v.1).  We have discussed that in the future modules could optionally declare a bigger (multiple) of page size in the memory section and then the page-count would, I assume, be interpreted as a count of the declared page size.  This would all be backwards-compatible, though, since the bigger page size was opt-in.

So since the binary format is being changed to use units of pages, I'd recommend doing the same for the text format.

**Comment by JSStats** [comment]
Could this be closed now?

**Comment by lukewagner** [comment]
It seems to still be the case that `memory_size` and `grow_memory` return units of bytes.

**Comment by rossberg-chromium** [comment]
Fixed a while ago.
