### ISSUE TITLE
Will wasm have a MIME type?

### ISSUE THREAD

**Issue by JoeArizona** [WebAssembly/spec#357]
What is the plan for MIME registration for WebAssembly? Assuming WebAssembly programs are delivered as discrete files, won't it need a type registration?

`application/wasm` would seem to make sense for the binaries.

If the textual format would benefit from its own MIME type, `text/wasm-source` works, and it mirrors the different MIME types for Java bytecode and Java source files.

**Comment by lukewagner** [comment]
That's a good question for when wasm is integrated with [`<script type='module'>`](https://html.spec.whatwg.org/multipage/webappapis.html#integration-with-the-javascript-module-system).  Until then, all wasm modules must be fetched manually as raw bits which are then fed into the [`Module` constructor](https://github.com/WebAssembly/design/blob/master/JS.md#webassemblymodule-constructor) or [`compile`](https://github.com/WebAssembly/design/blob/master/JS.md#webassemblycompile) as an `ArrayBuffer`.  When we we can load wasm directly from `<script>`, though, I agree defining a MIME type makes sense.

A close-related question is how to discriminate wasm vs. JS modules.  I see three options:
 1. distinguishing at the import site (e.g. `<script type="wasm">`, although there are other ways to load ES6 modules, and each would need some way to say "wasm")
 2. the MIME type of the response (which requires some server configuration)
 3. response content starting with the wasm magic word (`0x6d736100`), since the `0` first byte makes this invalid JS and so there is no ambiguity or need to sniff further than the first word

My preference is allowing 2 and 3 since 2 lets you be explicit but 3 will make it easier for devs to simply throw up wasm files on a server without having to configure the server.  As for 1, I think it's nice for a module-import-site not to have to care whether the imported module is JS vs. wasm; once wasm has [GC/JS/WebIDL integration](https://github.com/WebAssembly/design/blob/master/GC.md), wasm modules could drop-in-replace JS modules.

**Comment by rossberg-chromium** [comment]
Closing this for now. It's a fair question but outside the jurisdiction of the Wasm spec itself.
