### ISSUE TITLE
Support for trapping

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/spec#41]
[AstSemantics.md](https://github.com/WebAssembly/design/blob/master/AstSemantics.md) has the concept of a *trap*, which means
> execution [...] is terminated and abnormal termination is reported to the outside environment.

Several operators are defined to trap, such as integer division when the denominator is zero. What's the best way to represent this in OCaml? Would an exception be appropriate?

In the future, [trapping behavior may be made customizable](https://github.com/WebAssembly/design/blob/master/FutureFeatures.md#trapping-or-non-trapping-strategies), though I don't think it's necessary to try to anticipate this in the current code.

**Comment by rossberg-chromium** [comment]
An exception seems perfectly adequate. We can either just use the existing Error.error for that, or, if we care about distinguishing expected from unexpected runtime errors, introduce a new Eval.Trap exception.

**Comment by lukewagner** [comment]
It'd also be nice to add a new `(asserttrap (invoke ...))` command to test trapping behavior.

**Comment by lukewagner** [comment]
Given use of ML exceptions and ability to test with `assert_trap` (#74, #76), I think this issue is resolved, but feel free to reopen if there is more to do here.  When we specify JS<->wasm integration, we'll have to talk about how spec traps turn into JS exceptions (I assume), but I think that's outside ml-proto (it's just what the host does when Eval.invoke throws).
