### ISSUE TITLE
S-Expression Syntax

### ISSUE THREAD

**Issue by lgalfaso** [WebAssembly/spec#466]
At https://github.com/WebAssembly/spec/blame/master/interpreter/README.md#L271
the definition of a `module` does not allow `<typedef>` after `<func>`, nor `<func>` after `<table>`, but at https://github.com/WebAssembly/spec/blob/master/test/core/func.wast#L159 these two things happen.

Is the definition right and the test wrong or the other way around?

**Comment by rossberg-chromium** [comment]
The order of module fields is almost entirely free in the text format. The only restriction is that imports must come before actual definitions, in order to maintain their index space order. The grammar in the README is only approximate in that regard, mainly to keep it simple. I'm hoping to get round to specifying the text format properly this week or the next.

**Comment by jamen** [comment]
Ya been doing some awesome work @rossberg-chromium! :heart:

**Comment by rossberg-chromium** [comment]
I noted the free ordering in the README, and PR #471 is on the way, so closing this.
