### ISSUE TITLE
[spec] Inline memory export unclear

### ISSUE THREAD

**Issue by sphinxc0re** [WebAssembly/spec#693]
Under `Text Format > Modules > Memories`:

In the _Abbreviations_ section:

I'm having trouble understanding how the inline memory exports work. The inline data segment above doesn't require an appended `memtype`. But the import does. Does the export require that as well? How would such an export look like "unfolded" ?
Also, the use of the "..." is totally unclear to me.
<img width="751" alt="screen shot 2018-02-15 at 10 39 44" src="https://user-images.githubusercontent.com/3702016/36249957-ad98b562-123c-11e8-9103-546b5c13a570.png">
I want to add, that I already implemented most of the spec to a working parser. So I was able to understand most of it.
It would be awesome if you gave me a concrete example on how such a section would look like in `wast`

**Comment by rossberg** [comment]
The ellipses here and elsewhere are simply a placeholder for whatever (well-bracketed) sequence of tokens is there, and that is transported to the RHS unchanged. That may include stuff that requires more expansion (like additional import/export clauses).

However, the key point to note is that a program only is well-formed if it ultimately expands into a token sequence that is well-formed according to the kernel grammar. In this case (and some others) that necessarily implies that any `memory` declaration must end in a memtype, because otherwise it could not be expanded into something well-formed. You can use that invariant to multiply out all expansions into a full grammar. For example, the reference interpreter implements the text format through an [LR(1) grammar](https://github.com/WebAssembly/spec/blob/master/interpreter/text/parser.mly#L189), including [memory definitions](https://github.com/WebAssembly/spec/blob/master/interpreter/text/parser.mly#L562).

**Comment by sphinxc0re** [comment]
Thanks!
