### ISSUE TITLE
[spec review] 7 - Appendix

### ISSUE THREAD

**Issue by flagxor** [WebAssembly/spec#723]
Detail oriented review of draft text:
http://webassembly.github.io/spec/core/bikeshed/index.html#appendix%E2%91%A0

Try to be ready to discuss issues by the next in person WG meeting.

**Comment by eholk** [comment]
Some comments based on my review:

The algorithmic sub-steps (such as [here](http://webassembly.github.io/spec/core/bikeshed/index.html#-mathrminstantiate_module-hrefsyntax-storemathitstore-hrefsyntax-modulemathitmodule-hrefsyntax-externvalmathitexternvalast--hrefsyntax-storemathitstore-hrefsyntax-moduleinstmathitmoduleinst--hrefembed-errormathiterror)) look strange to me with the gray sidebar. Can we indent them instead? The gray bar makes me think they are block quotes or some other kind of notes. I like the way [this one](http://webassembly.github.io/spec/core/bikeshed/index.html#-mathrmget_export-hrefsyntax-moduleinstmathitmoduleinst-hrefsyntax-namemathitname--hrefsyntax-externvalmathitexternval--hrefembed-errormathiterror) is formatted much better.

When talking about memory sizes, should we use a variable like `page_size` instead of writing out 64 Ki? [example](http://webassembly.github.io/spec/core/bikeshed/index.html#-mathrmsize_mem-hrefsyntax-storemathitstore-hrefsyntax-memaddrmathitmemaddr--mathiti32)

The pseudo code in the [Validation Algorithm](http://webassembly.github.io/spec/core/bikeshed/index.html#a3-validation-algorithm) section should use a code font. The PDF version seems to, but it's a normal sans-serif variable width font in the bikeshed version.

In the [Name Section](http://webassembly.github.io/spec/core/bikeshed/index.html#name-section%E2%91%A0) description, it says "the name section is a custom sections" when it should say "the name section is a custom section."

In [Soundness](http://webassembly.github.io/spec/core/bikeshed/index.html#a5-soundness), it says "every function invocation always evaluates to a result of the right type (if it does not trap)." This should mention the possibility of nontermination too. WebAssembly does not guarantee all programs terminate.

Similarly, I found it odd that [host functions](http://webassembly.github.io/spec/core/bikeshed/index.html#host-function-instances--hrefsyntax-funcinstmathsftypehrefsyntax-functypemathitfunctype-hrefsyntax-funcinstmathsfhostcodemathithf) are also assumed to terminate, but since the execution of host functions is outside the theory this seems okay since it only specifies the conditions that must hold upon returning from a host function.

In the [rule for Frames](http://webassembly.github.io/spec/core/bikeshed/index.html#frames--hrefsyntax-framemathsflocalshrefsyntax-valmathitvalast-hrefsyntax-framemathsfmodulehrefsyntax-moduleinstmathitmoduleinst), the prose says t* is prepended to the locals variable, but the notation reads more like appending or replacing to me. Similarly in the [label](http://webassembly.github.io/spec/core/bikeshed/index.html#-hrefsyntax-labelmathsflabel_nhrefsyntax-instrmathitinstr_0asthrefsyntax-instrmathitinstrasthrefsyntax-instr-controlmathsfend) rule.

There is a broken reference in the note under [Store Extension](http://webassembly.github.io/spec/core/bikeshed/index.html#store-extension%E2%91%A0).

The [Theorems](http://webassembly.github.io/spec/core/bikeshed/index.html#theorems%E2%91%A0) section mentions resulttype in a couple of places, but it seems like this should instead be a reference to [result type](http://webassembly.github.io/spec/core/bikeshed/index.html#syntax-resulttype).

**Comment by rossberg** [comment]
Thanks for reviewing! PTAL at #792.

> The algorithmic sub-steps (such as here) look strange to me with the gray sidebar. Can we indent them instead? The gray bar makes me think they are block quotes or some other kind of notes. I like the way this one is formatted much better.

I think this was some Bikeshed weirdness that Brad fixed already.

> When talking about memory sizes, should we use a variable like page_size instead of writing out 64 Ki? example

Could do, but I'm not sure a definitional indirection makes it clearer. The proese explains and links it.

> The pseudo code in the Validation Algorithm section should use a code font. The PDF version seems to, but it's a normal sans-serif variable width font in the bikeshed version.

I think Brad fixed this one, too.

> In the Name Section description, it says "the name section is a custom sections" when it should say "the name section is a custom section."

Got fixed earlier.

> In Soundness, it says "every function invocation always evaluates to a result of the right type (if it does not trap)." This should mention the possibility of nontermination too. WebAssembly does not guarantee all programs terminate.

Done.

> Similarly, I found it odd that host functions are also assumed to terminate, but since the execution of host functions is outside the theory this seems okay since it only specifies the conditions that must hold upon returning from a host function.

Yes, you are right. I changed the condition so that it allows for the case of hf not ever returning.

> In the rule for Frames, the prose says t* is prepended to the locals variable, but the notation reads more like appending or replacing to me. Similarly in the label rule.

Yeah, Luke hat the same complaint, but after trying several different ways of "improving" the notation they all were worse, so I settled on more explanatory notes instead (in the main validation section).

> There is a broken reference in the note under Store Extension.

Fixed.

> The Theorems section mentions resulttype in a couple of places, but it seems like this should instead be a reference to result type.

Hm, I'm not sure I'm seeing it. Can you elaborate?

**Comment by eholk** [comment]
>>The Theorems section mentions resulttype in a couple of places, but it seems like this should instead be a reference to result type.
>
>Hm, I'm not sure I'm seeing it. Can you elaborate?

In the Progress theorem at http://webassembly.github.io/spec/core/bikeshed/index.html#theorems%E2%91%A0, the first mention of result type is spelled out and has a link to the definition ("valid with result type [t*]"). The second mention says resulttype though, with no link: "valid configuration with the same resulttype." It seems like these should be consistent.

**Comment by rossberg** [comment]
Ah, thanks! Fixed two occurrences.

**Comment by binji** [comment]
Seems that the issues here are fixed. Closing
