### ISSUE TITLE
[spec review] 6 - Text Format

### ISSUE THREAD

**Issue by flagxor** [WebAssembly/spec#724]
Detail oriented review of draft text:
http://webassembly.github.io/spec/core/bikeshed/index.html#text-format%E2%91%A0

Try to be ready to discuss issues by the next in person WG meeting.

**Comment by sbc100** [comment]
I'll take this one if you like.

**Comment by sbc100** [comment]
WIP document: https://docs.google.com/document/d/1goOh-DxqSTLVRau0-b2Lxc76qJ5G_HCPcHVd69fo-VI/edit?usp=sharing

**Comment by rossberg** [comment]
@sbc100, can you make that doc accessible without requiring a Google account to log in?

**Comment by sbc100** [comment]
Hmm, I can't seem to do that.  I will switch to some other format.

**Comment by sbc100** [comment]
Publicly accessible: https://docs.google.com/document/d/1tqibQhYQ-hTi7MqQE7rNaoF31_OnXdzSYHdRAOBD1GY/edit

**Comment by sbc100** [comment]
6.1

- Link attribute grammar to https://en.wikipedia.org/wiki/Attribute_grammar
- “source files containing WebAssembly modules in text format”: Seems a little redundant.  Drop the “source files?

6.1.1

- The following conventions are adopted in defining the grammar rules for of the text format.
- Terminal symbols are either literal strings of characters enclosed in quotes: ‘module’; or  - Not sure about the use of the colon and semicolon here.  Pehaps put `module` in brackets instead?
- T*  is a possibly empty sequence of iterations of T  - Seems odd because Tn on the previous line is also possible empty, but that isn’t mentioned there.

6.1.3

- The text format allows to use symbolic identifiers in…  “allows for the use of” or just “allows the use of”?

6.2.2

- Ifoccurringasaliteralterminalinthegrammar  - seems to be rendering issue here.
- in literal form ‘keyword’ in a syntactic production of this chapter.  Pur ‘keyword’ in brackets, perhaps preceded by e.g.?

6.2.3

- The only relevance of white space is to separate tokens, it is ignored otherwise.  This sort of sounds like it is two sentences.

6.2.4

- thenextcharactorisnot  - formatting issue?

6.3.3

- (ifc≥U+20∧c≠U+7F∧c≠‘"’c≠‘\’)  - missing ^ between final two clauses

6.3.4

- A name string must form a valid UTF-8 encoding as defined by Unicode (Section 2.5) that is interpreted as a string of Unicode code points.   This sentence doesn’t quite parse for me.  Perhaps “and is interpreted”?

6.5.2

- Typeuse appears here before is defined.  Not sure if this is an issue or not
- Are `nop` and `unreachable` really control instructions?  I guess so.

6.6.3

- In the final condition should the * be inside the {}?  like is is 6.6.5

6.6.2

- I expected to see a synthesized I` which included `id` in I’.types.

6.6.5.1

- Does “Moreover” make sense here?  Isn’t it normally used to elaborate on a previous sentence?

6.6.7.1

- Perhaps a little more emphasis on the singularity of the inline data and the fact that is must start at zero.  Maybe:  “A single data segment with zero offset can be given inline..”.
- Isn’t `KiB` the abbreviation of kibibyte?

6.6.11

- Test says table index is optional but I don’t see a ‘?’ in the rule.  If that is because it is the abbreviation that allows this then would it make more sense to mention the default value in the abbreviation section rather than here?

6.6.12

- Ditto

**Comment by rossberg** [comment]
Thanks for the review! PTAL at #791.

> 6.1
> 
> * Link attribute grammar to https://en.wikipedia.org/wiki/Attribute_grammar

Hm, we don't link any other technical terms (except where they define formats, like LEB128), so this would be an odd one out.

> * “source files containing WebAssembly modules in text format”: Seems a little redundant.  Drop the “source files?

Done.

> 6.1.1
> 
> * The following conventions are adopted in defining the grammar rules for of the text format.

Done.

> * Terminal symbols are either literal strings of characters enclosed in quotes: ‘module’; or  - Not sure about the use of the colon and semicolon here.  Pehaps put module in brackets instead?

Restructured.

> * T*  is a possibly empty sequence of iterations of T  - Seems odd because Tn on the previous line is also possible empty, but that isn’t mentioned there.

Well, the T_n case has it mentioned by saying "n <= 0".

> 6.1.3
> 
> * The text format allows to use symbolic identifiers in…  “allows for the use of” or just “allows the use of”?

Done.

> 6.2.2
> 
> * Ifoccurringasaliteralterminalinthegrammar  - seems to be rendering issue here.

This should be fixed by Brad's recent Bikeshed massaging.

> * in literal form ‘keyword’ in a syntactic production of this chapter.  Pur ‘keyword’ in brackets, perhaps preceded by e.g.?

Done.

> 6.2.3
> 
> * The only relevance of white space is to separate tokens, it is ignored otherwise.  This sort of sounds like it is two sentences.

Done.

> 6.2.4
> 
> * thenextcharactorisnot  - formatting issue?

Same here.

> 6.3.3
> 
> * (ifc≥U+20∧c≠U+7F∧c≠‘"’c≠‘\’)  - missing ^ between final two clauses

Done.

> 6.3.4
> 
> * A name string must form a valid UTF-8 encoding as defined by Unicode (Section 2.5) that is interpreted as a string of Unicode code points.   This sentence doesn’t quite parse for me.  Perhaps “and is interpreted”?

Done.

> 6.5.2
> 
> * Typeuse appears here before is defined.  Not sure if this is an issue or not

There is some mutual recursion in the grammar, so some forward references are unavoidable. Is it worth calling out?

> * Are nop and unreachable really control instructions?  I guess so.

At least that's how the design docs have always categorised them.

> 6.6.3
> 
> * In the final condition should the * be inside the {}?  like is is 6.6.5

Yep, well spotted!

> 6.6.2
> 
> * I expected to see a synthesized Iwhich includedid` in I’.types.

Because all module bindings are mutually recursive, module-level bindings need to be handled in a kind of pre-pass defined by the idc function at the bottom of section 6.6.13.

> 6.6.5.1
> 
> * Does “Moreover” make sense here?  Isn’t it normally used to elaborate on a previous sentence?

Removed here and in a few similar cases below.

> 6.6.7.1
> 
> * Perhaps a little more emphasis on the singularity of the inline data and the fact that is must start at zero.  Maybe: “A single data segment with zero offset can be given inline..”.

Done, here and for elem segments.

> * Isn’t KiB the abbreviation of kibibyte?

Yes, but here we just need the raw value 1024, no unit.

> 6.6.11
> 
> * Test says table index is optional but I don’t see a ‘?’ in the rule.  If that is because it is the abbreviation that allows this then would it make more sense to mention the default value in the abbreviation section rather than here?

Oops, yes, remainder of older formulation. Removed.

> 6.6.12
> 
> Ditto

Same here.
