### ISSUE TITLE
[spec review] 1 - Introduction + Consistency

### ISSUE THREAD

**Issue by flagxor** [WebAssembly/spec#725]
Detail oriented review of draft text:
http://webassembly.github.io/spec/core/bikeshed/index.html#introduction%E2%91%A0

Also includes front-matter + overall document consistency.

Try to be ready to discuss issues by the next in person WG meeting.

**Comment by lukewagner** [comment]
Random driveby:
* § 1.1: "WebAssembly is an open standard developed by a W3C Community Group that includes representatives of all major browser vendors." - This sentence was meaningful in early readmes/intros when wasm was just getting started but it seems out of place permanently backed into a W3C spec (especially once wasm starts showing up in non-browser embeddings)

**Comment by liminzhu** [comment]
Yeah I agree. Early on it was nice to show that all browsers were behind it but it's time for wasm to become a standard rather than perceived as a browser thing. Plus the standard is also technically developed by the WG? 

It's a small sample, but I looked up [service worker](https://www.w3.org/TR/service-workers-1/) and [webRTC](https://www.w3.org/TR/webrtc/) and none of them include similar text.

**Comment by liminzhu** [comment]
Did an attentive pass on intro and a rough pass at the rest of the core spec for consistency issues. Overall the spec is in very good shape! Some feedback:

* https://github.com/WebAssembly/spec/issues/759
* In 1.1 `Its main goal is to enable high performance applications on the Web, but it does not make any Web-specific assumptions or provide Web-specific features, so it can be employed in other environments as well.` Wasm does provide web specific features in JS and web spec, so I suggest,
 ..., but **the core spec** does not make any Web-specific assumptions ...
* nit - there are lots of arbitrary uses of colon or period before bullet points or formulas. (e.g. [1](http://webassembly.github.io/spec/core/bikeshed/index.html#dependencies①) [2](http://webassembly.github.io/spec/core/bikeshed/index.html#concepts①) [3](http://webassembly.github.io/spec/core/bikeshed/index.html#grammar-notation①) [4](http://webassembly.github.io/spec/core/bikeshed/index.html#auxiliary-notation①)). Maybe we can use colon in places where phrases like 'the following' or 'as follow' are used immediately before points or formulas and use period otherwise, or just apply some general principle. Certainly low pri as it doesn't really affect readability or anything much.

**Comment by rossberg** [comment]
Thanks for the review!

> * nit - there are lots of arbitrary uses of colon or period before bullet points or formulas. (e.g. 1 2 3 4). Maybe we can use colon in places where phrases like 'the following' or 'as follow' are used immediately before points or formulas and use period otherwise, or just apply some general principle. Certainly low pri as it doesn't really affect readability or anything much.

I tried to follow rules as I seemed to remember them from editing notes for articles, but I may well have messed it up. Happy to address concrete suggestions or review patches. :)

> * nit - If a footnote is displayed as a paragraph longer than a line, the number is placed next to the center of the paragraph rather than the start (example), which is a bit odd. Not sure if this is a bikeshed limitation or not.

It is. I opened #794 to track it.

**Comment by binji** [comment]
#794 is still not addressed, but it seems as though the rest of the issues are addressed. Closing.
