### ISSUE TITLE
Could the main spec landing pages link to the bikeshed page?

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/spec#751]
http://webassembly.github.io/spec/core/bikeshed/ is looking pretty good and has enormously faster cross-section navigation (of the type one does frequently when reading the spec).  Could we start linking to it from https://webassembly.github.io/spec/ and the sidebar of https://webassembly.github.io/spec/core/index.html?

**Comment by rossberg** [comment]
The landing page already links to it, just not as the main link. I would not feel comfortable with that yet, because it doesn't currently provide a good enough user experience. It is still lacking almost all hyper links for targeted navigation, misses content (esp the index tables), and has various rendering and layout issues. Also, at least on my ageing laptop, it in fact causes massive performance problems (freezing Chrome for several seconds after every couple of page downs).

**Comment by lukewagner** [comment]
Ah hah, I had totally missed the "Editor's Draft" link at the end of the line.  Thanks.  Makes sense to not make it primary or promote it too heavily until those issues are worked out.
