### ISSUE TITLE
[interpreter] rounding for floating-point constants

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/spec#809]
The interpreter currently rejects `(f32.const 0x1.fffffefffffff8000000p127)`, because it rounds the value up, out of the finite range of `f32`. Ideally, floating-point literals should be interpreter as if they were floating-point values with infinite precision, and then rounded in a single step to the expression type.

See also the background discussion [here](https://github.com/WebAssembly/spec/pull/807#discussion_r190149497).

**Comment by ericprud** [comment]
@sunfishcode, does the above merge close this issue?

**Comment by binji** [comment]
@ericprud No, this issue was added as a result of discussion on that PR. It's still a problem, but it's a minor one as it only affects how some floats are interpreted in the text format when given extra precision. 

It's perhaps not even an issue with the spec, but with the reference interpreter (and other tools). The spec clearly says that the value should be treated as infinite precision then rounded to the nearest (non-infinite) value, see http://webassembly.github.io/spec/core/text/values.html#floating-point.

**Comment by rossberg** [comment]
Parsing float literals via f64 exhibits a double rounding issue similar to the one from #421. Incorrect rounding to infinity is just one case.

#1025 adds various test cases, plus a gross hack to the interpreter to correct double rounding errors when parsing small floats (unfortunately, we cannot use a fix as simple as in #1021). PTAL
