### ISSUE TITLE
support Unicode(or UTF-8 encoded) identifiers

### ISSUE THREAD

**Issue by Zhang-Junzhi** [WebAssembly/spec#830]
I am wondering why wasm text format still doesn't support ientifiers outside of ASCII.

it's 2018, not 1998.

Why are English still the only allowed characters nowadays? *ALL* mordern languages support Unicode identifiers now. ALL.

So, please! Let's extend the allowed characters in identifiers to non-ASCII world.

**Comment by jfbastien** [comment]
If we do so, we should follow https://unicode.org/reports/tr31/

**Comment by binji** [comment]
The binary format already allows UTF-8 strings for the [import and export names](http://webassembly.github.io/spec/core/binary/values.html#names), as well as the [debug name section names](http://webassembly.github.io/spec/core/appendix/custom.html#name-section). The only limitation is in the [text format identifiers](http://webassembly.github.io/spec/core/text/values.html#text-id), as you've said, and that's primarily because it was simpler to do so and the text format is not really intended to be written, except for in spec tests where the identifiers are included for clarity.

That said, I think the group would support a proposal to add Unicode identifiers. The process for changing the spec is [here](https://github.com/WebAssembly/meetings/blob/master/process/phases.md).

**Comment by steveklabnik** [comment]
We’re heavily investigating this in Rust right now; I’m not at a computer or I’d give you a link, but the proposal thread has a LOT of background on the problem space here.

**Comment by 7ombie** [comment]
Is this still planned? I don't have much use for it personally, so am not worried about the timeframe, but am interested to know if anything concrete has been decided, either way.

**Comment by rossberg** [comment]
Nobody has pushed for it by means of a concrete proposal, so no, currently there are no plans.

**Comment by 7ombie** [comment]
Thank you, @rossberg. No worries.
