### ISSUE TITLE
[jsapi] Should MemoryDescriptor["initial"] be required?

### ISSUE THREAD

**Issue by Ms2ger** [WebAssembly/spec#838]
Somewhat simplified, the spec has:
```
dictionary MemoryDescriptor {
  required [EnforceRange] unsigned long initial;
};

[Constructor(MemoryDescriptor descriptor)]
interface Memory {
};
```

but then the prose goes on to say

> If descriptor["initial"] is present, let initial be descriptor["initial"]; otherwise, let initial be 0.

while this line is unreached if descriptor["initial"] is not present, because IDL will throw an exception before calling into the spec's prose.

**Comment by binji** [comment]
Yes, I think initial should be required. So I suppose it makes sense to remove the `If descriptor["initial"] is present,` part.

**Comment by littledan** [comment]
To be clear here, I believe this was optional in the previous informal spec, and marked as required because bikeshed's WebIDL linter was complaining. I don't know if it is web-compatible to be required.

**Comment by Ms2ger** [comment]
SpiderMonkey throws, V8 and JSC don't.

The linter was likely complaining about the lack of `optional` on the `descriptor` argument. (WebIDL insists that web developers are not required to pass a trailing empty object argument, so requires the `optional` keyword on a dictionary argument if there's no required fields.)

**Comment by lukewagner** [comment]
From my reading of [the SM code](https://hg.mozilla.org/mozilla-central/file/tip/js/src/wasm/WasmJS.cpp#l448), we don't throw when we see the property is missing, but rather due to the [EnforceRange] attribute which fails because `undefined` gets coerced via ToNumber to `NaN` which fails the IsFinite check.

**Comment by lukewagner** [comment]
Oh, and to finish that thought: as long as we still have [EnforceRange], I think we should make the attribute required.

**Comment by Ms2ger** [comment]
Note that the same applies to `maximum`. If we remove the `required` keyword, you'll have to add a check for `undefined` before coercing the value with `ToNumber`.

**Comment by lukewagner** [comment]
Ah, interesting.  If a property is marked as `optional`, will the [EnforceRange] only take effect when the property is present?  That's the semantics we need.

**Comment by Ms2ger** [comment]
Yes, exactly.

**Comment by lukewagner** [comment]
Great, so then to summarize it seems like `initial` would stay `required` and `maximum` would be changed to `optional`.

**Comment by Ms2ger** [comment]
`maximum` is already optional. Why should `initial` be required?

**Comment by lars-t-hansen** [comment]
> `maximum` is already optional. Why should `initial` be required?

Because while it's common to create a memory without a maximum, creating a memory without an initial size is almost certainly an error.  IMO the descriptor argument should be required for the same reason.  (Of course web compat may preclude that, but that's incidental.)  The "convenience" of the optional descriptor argument and optional initial property is in reality just a footgun.

**Comment by lukewagner** [comment]
> maximum is already optional. Why should initial be required?

Ah, maybe I'm looking at a stale doc then, but in https://webassembly.github.io/spec/js-api/index.html#memories, `initial` is already `required` and I didn't see `optional` on `maximum` (but maybe that's the default if you don't say `required`?).

**Comment by littledan** [comment]
@lukewagner That's right--in WebIDL, I believe dictionaries default to optional and note required, whereas parameters default to required and note optional.

**Comment by xtuc** [comment]
In JS if `initial` is now required that would be a breaking change but In Wasm's Memory Type, it's required.

Following @lars-t-hansen comment about footgun; when you import a WebAssembly.Memory and the initial is smaller that the one declared in Wasm, it throws. So I think this kind of the errors will be catched. 

Also, I would be happy to send a PR if once we have a resolution.

**Comment by littledan** [comment]
Is a PR needed? Maybe we should stick with the current semantics, per the comments from @lars-t-hansen . Otherwise, if we want to stick with WebIDL conventions while preserving the optionality, I guess we would make the dictionary field optional *and* the existence of the dictionary parameter optional.

**Comment by xtuc** [comment]
A PR is need in all cases because the spec has the two conflicting behaviors.

**Comment by littledan** [comment]
Right, of course. Does anyone want to make a PR to delete the dead line that @Ms2ger mentions?
