### ISSUE TITLE
Testsuite checks a 4GiB memory limit despite the spec not enforcing it.

### ISSUE THREAD

**Issue by Kimundi** [WebAssembly/spec#861]
Tests like https://github.com/WebAssembly/spec/blob/master/test/core/memory.wast#L52 check that a memory with a size larger than 4 GiB get rejected by the validation, but the actual spec does not enforce that limit at either the validation of a [module](https://webassembly.github.io/spec/core/valid/modules.html#valid-module), a [memory](https://webassembly.github.io/spec/core/valid/modules.html#valid-mem) or a [memtype](https://webassembly.github.io/spec/core/valid/types.html#valid-memtype).

**Comment by rossberg** [comment]
Good catch, this constraint seems to be missing in the spec. I'll prepare a fix.

**Comment by pepyakin** [comment]
While we are all here let's ask [the full question](https://github.com/CraneStation/wasmtime/pull/13#discussion_r209570801) : )

What about dynamic growing? So, for example, there is a module that has a linear memory instance which has no maximum limit. Seems like growing memory dynamically (say via `memory.grow`) past 4GB (or any other limit) seems to be allowed by the spec (both written and the interpreter), even though that memory is not accessible from the inside of wasm (since 32bit pointer + 32bit unsigned offset gives you at most 8GB). So I want to confirm, is that correct and intended?

**Comment by rossberg** [comment]
Ah, interesting. That should fail, and the test suite actually has [a test for that](https://github.com/WebAssembly/spec/blob/master/test/core/memory_grow.wast#L46), too. But the check was also missing in the spec.

I extended PR #862 to include the check as well, plus an additional test.

**Comment by Kimundi** [comment]
I guess this can be closed now :)
