### ISSUE TITLE
Review the maximum size of a function body

### ISSUE THREAD

**Issue by Ms2ger** [WebAssembly/spec#935]
> The maximum size of a function body, including locals declarations, is 7654321 bytes.

Let's use a round number.

**Comment by littledan** [comment]
This constant has some interesting history; see https://github.com/WebAssembly/spec/issues/607#issue-277476473 . It used to be unenforced (in multiple browsers, due to separate bugs!), so it had to be raised to meet web reality.

What's the need for a round number? To me, this one seems as good as any; the important thing is that it be the same everywhere.

**Comment by binji** [comment]
Agreed that this number is "cute", but since it's (nearly) arbitrary we can afford to be cute here. :-)

Closing, but feel free to reopen if there is more to discuss here.
